var extractTextCss=require('extract-text-webpack-plugin');
module.exports= {
	entry:{
	 app:"./app.js",
	},
	output:{
		path:__dirname+"/src/dist",
		filename:"./[name].bundle.js"
	},
 	resolve:{
     alias: {
       a2:"./js/app2.js",
     }
 	},
	module:{
		rules: [
     {
       test:/\.less$/,
       use:extractTextCss.extract({
        fallback:{
           loader:'style-loader',
           options:{
            //insertInto:"#mydiv",
            singleton:true,
            //transform:"./transform.js"
           }
         },
          use:[       
           {
             loader:'css-loader',
             options:{
               modules:{
                localIdentName:'[path][name]_[local]_[hash:4]'
               }                    
             } 
           },
           {
             loader:'postcss-loader',
             options:{
              ident:'postcss',
              plugins:[
               require('autoprefixer')(),
               require('postcss-cssnext')()
              ]
             }
           },
           {
            loader:'less-loader'
           }        
          ]         
       })
     }
		]
	},
  plugins:[
   new extractTextCss({
    filename:'[name].min.css'
   })
  ]
}